clientes/urls.py
from django.urls import path

from . import views

app_name = 'clientes'

urlpatterns = [
    path('list/', views.cliente_list, name='cliente_list'),
    path('new/', views.cliente_new, name='cliente_new'),
    path('update/<int:id>/', views.cliente_update, name='cliente_update'),
    path('delete/<int:id>/', views.cliente_delete, name='cliente_delete'),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home')
]

django_gpacheco/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [    
    path('', include('core.urls', namespace='core')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('clientes/', include('clientes.urls', namespace='clientes')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientes/models.py
from django.db import models


class Cliente(models.Model):
    SEX_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
    )
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    sex = models.CharField('Sexo', max_length=1, choices=SEX_CHOICES)    
    age = models.IntegerField()
    salary = models.DecimalField(max_digits=5, decimal_places=2)
    bio = models.TextField()
    photo = models.ImageField(upload_to='clinets_photos', null=True, blank=True)

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
    
    def __str__(self):
        return self.first_name + ' ' + self.last_name

core/models.py
from django.db import models

# Create your models here.

clientes/forms.py
from django.forms import ModelForm

from .models import Cliente


class ClienteForm(ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'

clientes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import ClienteForm
from .models import Cliente


@login_required
def cliente_list(request):
    clientes = Cliente.objects.all()
    return render(request, 'list.html', {'clientes': clientes})


@login_required
def cliente_new(request):
    form = ClienteForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect('clientes:cliente_list')    
    return render(request, 'new.html', {'form': form})


@login_required
def cliente_update(request, id):
    cliente = get_object_or_404(Cliente, pk=id)
    form = ClienteForm(request.POST or None, request.FILES or None, instance=cliente)
    if form.is_valid():
        form.save()
        return redirect('clientes:cliente_list')
    return render(request, 'new.html', {'form': form})


@login_required
def cliente_delete(request, id):
    cliente = get_object_or_404(Cliente, pk=id)
    if request.method == 'POST':
        cliente.delete()
        return redirect('clientes:cliente_list')
    return render(request, 'cliente_delete_confirm.html', {'cliente': cliente})

core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

clientes/templates/cliente_delete_confirm.html
{%  extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
    {{ block.super }} Deletar
{% endblock title %}

{% block body %}
<div class="container">    
    <div class="row">
        <div class="col-md-12">
            <h1>Deseja deletar o registro: {{ cliente.first_name }}</h1>
            <form action="." method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Deletar</button>
            </form>
            <br/>
            <a href="{% url 'clientes:cliente_list' %}" class="btn btn-primary btn-sm">Voltar</a>
        </div>
    </div>
</div>    
{% endblock body %}

clientes/templates/list.html
{%  extends 'base.html' %}

{% block title %}
    {{ block.super }} Listagem de Clientes
{% endblock title %}

{% block body %}

<div class="container">
    <h1>Listagem de Clientes</h1>

        {% if user.is_authenticated %}
            Bem Vindo {{ user.username }}!
            <p><a href="{% url 'logout' %}" class="btn btn-primary btn-sm">Log Out</a></p>
        {% endif %}        

    <div class="row">
        <div class="col-md-12">
            <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Último nome</th>
                    <th scope="col">Sexo</th>
                    <th scope="col">Idade</th>
                    <th scope="col">Salário</th>
                    <th scope="col">Bio</th>
                    <th scope="col">Ações</th>
                  </tr>
                </thead>
                <tbody>
                {% for cliente in clientes %}
                    <tr>
                        <th scope="row">{{ cliente.id }}</th>
                        <td>{{ cliente.first_name }}</td>
                        <td>{{ cliente.last_name }}</td>
                        <td>{{ cliente.sex }}</td>
                        <td>{{ cliente.age }}</td>
                        <td>{{ cliente.salary }}</td>
                        <td>{{ cliente.bio }}</td>
                        <td>
                            <a href="{% url 'clientes:cliente_update' cliente.id %}" class="btn btn-primary btn-sm">Editar</a>
                            <a href="{% url 'clientes:cliente_delete' cliente.id %}" class="btn btn-danger btn-sm confirm-delete">Excluir</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
    <a href="{% url 'clientes:cliente_new' %}" class="btn btn-primary btn-sm">Novo</a>
</div>

{% endblock body %}

clientes/templates/new.html
{%  extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
    {{ block.super }} Cliente
{% endblock title %}

{% block body %}
<div class="container">
    <h1>Cliente</h1>
    <div class="row">
        <div class="col-md-12">
            <form action="." method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.first_name.id_for_label }}">Nome</label>
                    {{ form.first_name|add_class:"form-control"|attr:"autofocus" }}
                </div>

                <div class="form-group">
                    <label for="{{ form.last_name.id_for_label }}">Último nome</label>
                    {{ form.last_name|add_class:"form-control" }}
                </div>
                
                <div class="form-group">
                    <label for="{{ form.sex.id_for_label }}">Sexo</label>
                    {{ form.sex|add_class:"form-control" }}
                </div>
                                
                <div class="form-group">
                    <label for="{{ form.age.id_for_label }}">Idade</label>
                    {{ form.age|add_class:"form-control" }}
                </div>

                <div class="form-group">
                    <label for="{{ form.salary.id_for_label }}">Salário</label>
                    {{ form.salary|add_class:"form-control" }}
                </div>

                <div class="form-group">
                    <label for="{{ form.bio.id_for_label }}">Bio</label>
                    {{ form.bio|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.photo.id_for_label }}">Foto do perfil</label>
                    {{ form.photo|add_class:"form-control-file" }}
                </div>

                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>
        </div>
    </div>
</div>    
{% endblock body %}

core/templates/home.html
{%  extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
    {{ block.super }} Seja Bem vindo
{% endblock title %}

{% block body %}
<div class="container">
    <h1>Seja Bem vindo</h1>
    <div class="row">
        <div class="col-md-12">
            {% if user.is_authenticated %}
                Bem vindo {{ user.username }}!
                <p><a href="{% url 'logout' %}" class="btn btn-primary btn-sm">Log Out</a></p>
            {% else %}
                <p>Realize o login</p>
                <a href="{% url 'login' %}" class="btn btn-primary btn-sm">Log In</a>
            {% endif %}
        </div>
    </div>
</div>    
{% endblock body %}

templates/base.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>{% block title %} Gestão de Cliente | {% endblock title %}</title>
</head>
<body>

    {% block body %}
    
    {% endblock body %}

    <script src="{% static 'js/bootstrap.js' %}"></script>    
</body>
</html>